global:
  scrape_interval: 15s

scrape_configs:
  # - job_name: "gdg-leaderboard"
  #   metrics_path: /api/v1/metrics
  #   static_configs:
  #     - targets: ["host.docker.internal:8998"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]
