# @TODO install and setup certbot for SSL certificates and listed domains
# - gdgtiu.dev
# - www.gdgtiu.dev
# - email.gdgtiu.dev
# - api.gdgtiu.dev
# - devx.gdgtiu.dev
# - leaderboard.gdgtiu.dev
# - metrics.gdgtiu.dev

---
- name: Install and setup certbot for nginx
  tasks:
    - name: Install certbot
      apt:
        name: certbot
        state: present
      become: true
      when: ansible_os_family == "Debian"

    - name: Install python3-certbot-nginx
      apt:
        name: python3-certbot-nginx
        state: present
      become: true
      when: ansible_os_family == "Debian"

    - name: Obtain SSL certificates
      command: >
        certbot --nginx
        -d gdgtiu.dev
        -d www.gdgtiu.dev
        -d metrics.gdgtiu.dev
        -d api.gdgtiu.dev
        -d leaderboard.gdgtiu.dev
        -d email.gdgtiu.dev
        -d devx.gdgtiu.dev
      become: true
      register: certbot_output
      ignore_errors: yes
      when: ansible_os_family == "Debian"
